version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
  pre_build:
    commands:
      - npm install
  build:
    commands:
      - npm run build
      - npm run cdk -- synth
  post_build:
    commands:
      - echo Build completed on `date`

artifacts:
  base-directory: cdk.out
  files:
    - '**/*'